{% set version = "2.3.0" %}

package:
  name: depfinder
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/depfinder/depfinder-{{ version }}.tar.gz
  sha256: 2694acbc8f7d94ca9bae55b8dc5b4860d5bc253c6a377b3b8ce63fb5bffa4000

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  entry_points:
    - depfinder = depfinder.cli:cli

requirements:
  host:
    # Python version is limited by stdlib-list.
    - python <3.9
    - pip
  run:
    - python <3.9
    - stdlib-list
    - pyyaml

test:
  commands:
    - depfinder -h
  imports:
    - depfinder

about:
  home: http://github.com/ericdill/depfinder
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Find all the unique imports in your library

extra:
  recipe-maintainers:
    - ericdill
    - mariusvniekerk
    - tonyfast
    - ocefpaf
