travis:
  secure:
    BINSTAR_TOKEN: dk71P8RmgRNkLd49KVmalGPHgFa98RZqcl8Nr2qpNH3peEpHjQ5xYdbB26lI8sDL5tPKMAXhUpJzipIqEAWKGX0xfmwWVQJSGhPM0luymrKp0FoIv1CTK0Wbvp+Cr0aAUlG6CAf0ObHjLOr7BGHmXfZclgTiGm1+ZJ5D1HlRQmvveIHBq3qBVlVIYo3nwfbR15ZwQIm2ivmrohBwP02u7VbFBzFPbCKavGiaV6RCDGtRlMaVvdrwCwe2aaPa87J2i7Hm0aJLgeEmMpYyBUPUEvyP+L5uUW7Y9lg6WwVkdJfeKcsTAm7Zqqdl3o4XgT3XINCudXYG5zWvqhJ564n1VidcBAVDCQlaghixqGmqXFFHMjEReDE4PgSUOoySd5KxZMH4kT5YbC5rZUD7BmiHjFv0qM2z9nZKXmMEUtQd76ZOJoBaynVcfbg3fnSFhxBpU2ZQu1VM2iuaCjpAtBs2zB4tETVGLCFS/LW8gei5UoiN+zETmDSrkhG7Ph9kQ31oQC/MF8CuCQEi9sukL7WdEvK3VY8QnGqwCMraMuhAvueBSHZb+4mAr3SNdbqRkByyzIYSTl/So7KtYIA29jgXclTpZelTt7BbLGp6yv6fMduPmI7R+SpzmjQ2Lz1P6R83HT8IF/8hNG34sIsOpQPjTRsN1E71ZXpQBk+AMUlQfjg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
