travis:
  secure:
    BINSTAR_TOKEN: e6QEGtr9Q530GXuq5/g1yDsurSA37OpgpZL5ztR1jrByQ/Fxd202jj+/avF+HwxmHZg2/kgYIplcuYz6qkmM930FDUnV7/rYbzKETdrf8epKvUQTZO3wtwmQBFwOfTMR0Tac2TdPjLkqRJdZDF1THMCBml3QIP10eFLysIptr1q9pbOym88rTZp6yLDjsCpyJzhZHYNIugyX7ySOmD6ZeFelw0+Fw7lErLhWJr2KFAZBCQ6tRb2sCH4CJyzFz6G5FUCDqrBZ/M+7DsIFE1bNRh4hPFayJ3krO4pSMQD8G/yNVKO7bycBj3x8jTWX/lCwH2SQfDrH1jGmbVyRIqn5L/Bo4XpOZM8c62CSXCkmAssZgwTdnBV1GiEjR0sPhSNVTCitA/n6cNHwsLLZrY44Y1cBzg2ZoJklmiaj5bmtNAhALToIrmyTa/BUfd+pcDKoNsL7s/MTGNI7NB7sSVTRhg2bzxGuJebfusky/uOrrK0N3ktImV+vJsNmYoCpyB8o5AjF2tTILKgr/1aDmYddGf/oxe+62CiY6hOzCI1/ylIVAhgd3Cn+PfocRZsCnHF3bvhamcVfJOFju5lw7cLyRZpXS9NEEk+T1qt67mlg4ih/GHoPzdJ4DbrXY6ObV8rQjOMDnDru9O6hCJyGyS/GcrUb48fy7OTWpzke+LOMqzg=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
